import type { CSSProperties } from "react";

/**
 * A section's own strip of light, behind its title block.
 *
 * The landing hero got an atmospheric background and it was the single change that made
 * the site feel finished rather than merely correct. This is the same substance in the
 * shape the instrument pages can safely take: a short band at the TOP of the page, behind
 * the title and nothing else. No table, chart or receipt is ever read through it.
 *
 * A STYLE, NOT A COMPONENT, and that is the whole design of this file.
 *
 * The first version was a <div> positioned absolutely inside <main>. Absolutely positioned
 * elements paint ABOVE in-flow siblings, so it landed on top of the page title, the source
 * chip and the warning banner and washed all three out. The hero had already taught this
 * once, from the other direction: there it was given a negative z-index instead, which put
 * it behind the body's own background and rendered nothing at all.
 *
 * Both failures are the same mistake — trying to place a decorative layer in the stacking
 * order relative to content. A background layer has no stacking order to get wrong. So
 * this returns a style for the element that already wraps the content.
 *
 * IT DEGRADES TO NOTHING. A background-image that 404s renders as plain ground: no broken
 * icon, no layout shift, no console error. The four header images are generated by hand
 * and dropped into public/art, and every page is correct before, during and after that
 * happens rather than only at the end.
 *
 * THREE LAYERS, front to back: a horizontal fade dissolving the left and right edges so
 * the band is not a visible rectangle the width of the content column; a vertical fade
 * ending it before the content; then the image. All three are the same height, because a
 * fade can only dissolve what it is drawn over — getting that wrong on the hero left a
 * hard seam across the page.
 */
export function pageBand(src: string): CSSProperties {
  return {
    backgroundImage:
      "linear-gradient(to right, var(--color-ground) 0%, transparent 16%, transparent 84%, var(--color-ground) 100%), " +
      "linear-gradient(to bottom, color-mix(in srgb, var(--color-ground) 55%, transparent) 0%, color-mix(in srgb, var(--color-ground) 84%, transparent) 62%, var(--color-ground) 100%), " +
      `url(${src})`,
    backgroundSize: "100% 13rem, 100% 13rem, 100% 13rem",
    backgroundPosition: "center top, center top, center top",
    backgroundRepeat: "no-repeat, no-repeat, no-repeat",
  };
}
