import type { Metadata } from "next";
import Script from "next/script";
import Link from "next/link";
import { NavLink } from "@/components/NavLink";
import { WalletChip } from "@/components/WalletChip";
import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { DemoBanner } from "@/components/DemoMode";
import { StatusBar } from "@/components/StatusBar";
import { Theme } from "@/components/Theme";
import { Footer } from "@/components/Footer";

/**
 * TWO faces now, not three. Newsreader is gone.
 *
 * A light serif at display size over a monospace table is what made this read as an essay
 * with an appendix rather than as one instrument, and `--font-display` now resolves to
 * Plex Sans like `--font-sans` does. Headings carry their weight instead of their shape.
 * The saved fetch is a real one: it was a whole extra family for headings alone.
 *
 * The faces ui-spec.md section 2.1 specifies, actually loaded.
 *
 * They were not. `globals.css` named Newsreader and IBM Plex in its font stacks and
 * nothing ever fetched them, so every visitor got the fallbacks -- Georgia for the
 * display face, the system UI sans for body, and Consolas for every chain value. The
 * mono fallback is the one that mattered: `font-variant-numeric: tabular-nums` is why
 * a countdown does not shuffle its neighbours as digits change, and Consolas gives
 * that only by accident of being fixed-width.
 *
 * `next/font` self-hosts them at build time, so the shipped page makes no request to
 * Google -- which the static essay does, and which is a third-party dependency a page
 * arguing for verifiability should not need. The cost is that `next build` needs the
 * network once; that fails loudly and immediately, which is the failure mode to prefer.
 */
const sans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"], // not a variable font: the weights must be named
  variable: "--font-plex-sans",
  display: "swap",
});

const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-plex-mono",
  display: "swap",
});

/**
 * The origin the link card is resolved against.
 *
 * og:image has to be absolute, so Next needs a base. NEXT_PUBLIC_SITE_URL wins if it is
 * set; otherwise Vercel's own VERCEL_URL, which it injects per deployment, including
 * previews. Falling back to localhost rather than guessing a production domain is
 * deliberate: a wrong absolute URL in og:image is worse than an obviously local one,
 * because it fails silently in someone else's chat window instead of in your own.
 */
const origin =
  process.env.NEXT_PUBLIC_SITE_URL ??
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "http://localhost:3000");

export const metadata: Metadata = {
  metadataBase: new URL(origin),
  title: "Glasshouse — taker priority by sealed bid",
  description:
    "A sealed-bid, second-price auction for the right to fill an order. A custom 1inch SwapVM instruction, live on Base.",
  openGraph: {
    type: "website",
    siteName: "Glasshouse",
    title: "Glasshouse — taker priority by sealed bid",
    description:
      "The winner bids 400 bps and pays 250, the runner-up's price. The difference goes to the maker. A custom 1inch SwapVM instruction, live on Base.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Glasshouse — taker priority by sealed bid",
    description:
      "The winner bids 400 bps and pays 250, the runner-up's price. The difference goes to the maker.",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable}`}>
      <body className="bg-ground text-ink antialiased">
        {/* The round manifest and the cold-fallback snapshot are classic scripts, loaded
            before hydration, because they assign globals the data layer reads. They are
            generated files (scripts/make-snapshot.mjs) and deliberately not imported as
            modules: the snapshot must also work when opened from a file, where fetch of a
            sibling fails. */}
        <Script src="/data/rounds.js" strategy="beforeInteractive" />
        <Script src="/data/snapshot.js" strategy="beforeInteractive" />
        {/* The independent verifier's last run, so the evidence page can show what it found
            without a reader needing a terminal. Generated by verify-run.mjs --emit. */}
        <Script src="/data/verification.js" strategy="beforeInteractive" />
        <Providers>
          <Theme>
          <div className="mx-auto max-w-6xl px-5 py-6">
            <header className="mb-8 flex flex-wrap items-baseline justify-between gap-4 border-b border-rule pb-4">
              {/* A WORDMARK, AND NOW ONLY THAT.
                  It used to carry `/ 1inch SwapVM / opcode 0x2e` beside it on every page.
                  The lineage is worth claiming -- it is the whole novelty -- but not on the
                  one line a visitor actually reads, where it competed with the product's own
                  name for the same glance. It says it once now, in the footer, under a
                  sentence that says what the thing does. */}
              <Link href="/" className="group flex items-baseline gap-2.5">
                <span className="font-display text-base font-semibold tracking-[0.02em] text-ink group-hover:text-glass">
                  GLASSHOUSE
                </span>
              </Link>
              {/* NavLink marks the page you are on (DESIGN.md F-6). Four identical links
                  gave a visitor arriving from a shared link no way to tell where they had
                  landed, which is the cheapest orientation cue there is.

                  FOUR ENTRIES, AND `Bidders` IS NOT ONE OF THEM. /account answers "what has
                  this address done", which is a question you ask ABOUT something you are
                  already looking at -- and every address on the site is already a link to
                  its own profile. As a top-level destination it was a page you arrive at
                  with an empty form and nothing to type into it. The footer keeps it as
                  "Look up an address", which is what it is for.

                  FAQ IS NEW AND IS NOT AN APPENDIX. Every instrument panel that needs to
                  explain itself deep-links into /faq#anchor, so it has to be reachable from
                  the nav for the same reason Evidence is: a reader who wants the mechanism
                  rather than the numbers has somewhere to go that is not the essay. */}
              <nav className="flex flex-wrap items-center gap-x-6 gap-y-2 text-[0.8125rem] font-medium text-ink-soft">
                <NavLink href="/">Live</NavLink>
                <NavLink href="/rounds">Rounds</NavLink>
                <NavLink href="/evidence">Evidence</NavLink>
                <NavLink href="/faq">FAQ</NavLink>
                {/* AFTER the nav and visually quieter than it, because connecting is
                    optional here and the placement should say so. Reading this site needs
                    no wallet; only bidding does, and that rule is one of the better
                    decisions in the product -- a page arguing you do not have to trust it
                    should not ask you to sign something before it will show you why. The
                    control was previously on /board alone, so on four of five pages there
                    was no sign that bidding existed at all. */}
                <span className="ml-1 border-l border-rule pl-5">
                  <WalletChip />
                </span>
              </nav>
            </header>
            {/* The provenance line, on every page, so any screenshot carries it. The
                rehearsal toggle and the connected address live in it -- the control that
                changes the source belongs on the line that names the source. */}
            <StatusBar />
            {/* Not dismissible. ui-spec.md 3.5 rule 3: a data state that is not live
                raises a banner, not just a chip. */}
            <DemoBanner />
            {children}
            {/* One footer, on every route, and the only place on the site that states the
                product in one sentence. It replaced three lines of mono that printed two
                addresses in full and named a dependency -- true, and not one of the four
                things a reader arriving cold needs. */}
            <Footer />
          </div>
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
