"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useBoard } from "@/components/BoardProvider";
import { SourceChip } from "@/components/Auction";
import { RoundsTable } from "@/components/RoundsTable";
import {
  ROUND_FILTERS,
  RoundsFilterTabs,
  unreadableCount,
  type RoundFilterId,
} from "@/components/RoundsFilter";
import { Loading } from "@/components/Loading";

/**
 * The rounds/history view.
 *
 * A client component, not a server one reading data at build time: `next.config.mjs` sets
 * `output: "export"`, so there is no server to do that read on, and no `generateStaticParams`
 * / dynamic route either -- this whole page is one static shell that fetches after it loads
 * in the visitor's own browser, same as the live board.
 *
 * useBoard() already IS the "read history" path as well as the "watch live" path: its
 * only source today is a direct eth_call per round, falling back to the checked-in
 * snapshot. That is a CHOICE, not a limitation -- the subgraph has been published to The
 * Graph Network since 2026-09-11 and answers queries -- and the reason is in
 * useAuctions.ts: a phase that ticks needs the chain head, and an indexer is a block or
 * two behind it. This page does not invent a second data path -- it renders the same board
 * data as a table instead of cards, plus the provenance the live board doesn't need
 * repeated per-card.
 */
export default function RoundsPage() {
  const { auctions, head, source, isFork, loading, error, refresh } = useBoard();

  // The selected filter lives in state rather than the URL. A shareable /rounds?filter=
  // would be better and is a deliberate omission for now: `useSearchParams` forces a
  // Suspense boundary in a static export, and the one on /evidence already cost this
  // project six prerendered figures down to two before it was caught
  // (see the note at the top of app/evidence/page.tsx). Not worth re-learning that here
  // for a filter whose default shows everything.
  const [filterId, setFilterId] = useState<RoundFilterId>("all");
  const filter = ROUND_FILTERS.find((f) => f.id === filterId) ?? ROUND_FILTERS[0];
  const shown = useMemo(
    () => auctions.filter((a) => filter.match(a, head)),
    [auctions, head, filter],
  );
  const unreadable = unreadableCount(auctions);

  const caption =
    source === "chain"
      ? `useBoard() in web/lib/useAuctions.ts, reading GlasshouseBook (0xc4ea91Fe700918220423ac307C6B1c59650FFbfe) on Base directly over eth_call -- once per round listed in public/data/rounds.js -- as of block ${head.toLocaleString("en-US")}. Not the subgraph: it is published and served, but a phase that ticks needs the chain head, and an indexer is a block or two behind it.`
      : source === "snapshot"
        ? `public/data/snapshot.js, generated by scripts/make-snapshot.mjs from GlasshouseBook logs on Base, as of block ${head.toLocaleString("en-US")}. The live chain read that normally powers this page returned nothing this session, so this is history rather than a live view -- the source chip above says so, not just this line.`
        : source === "sim"
          ? // The rehearsal reaches this page too, because it drives the same shared board.
            // Without this arm the caption below a table of simulated rounds read "nothing
            // has loaded yet", which is both wrong and the wrong KIND of wrong.
            `web/lib/simulate.js, replaying scripted rounds through the contract's own clearing rule at one block per 0.4 s. NOTHING HERE WAS READ FROM A CHAIN: the block numbers count from a chosen origin and are not Base blocks, and the addresses belong to no one. Turn the rehearsal off in the header to see the real rounds.`
          : "Nothing has loaded yet: no chain read has returned and this build carries no fallback snapshot.";

  return (
    <main className="mx-auto max-w-[62rem] px-4 py-10 sm:px-6">
      <div className="flex flex-wrap items-baseline justify-between gap-x-6 gap-y-2">
        <div>
          <h1 className="font-display text-3xl text-ink">Rounds</h1>
          <p className="mt-1 text-sm text-ink-soft">
            Every round this build knows about, newest first. For the round in progress right
            now, see the live board.
          </p>
        </div>
        <Link
          href="/"
          className="whitespace-nowrap text-sm text-glass underline decoration-rule underline-offset-2 hover:decoration-glass"
        >
          ← live board
        </Link>
      </div>

      <figure data-src={source} className="mt-8">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <SourceChip source={source} head={head} isFork={isFork} />
          <button
            type="button"
            onClick={refresh}
            className="rounded-control border border-rule px-2 py-1 font-mono text-[0.7rem] uppercase tracking-[0.12em] text-ink-soft hover:border-glass hover:text-glass"
          >
            refresh
          </button>
        </div>

        {/* Loading and error are real states here, not a blank table. A skeleton or a
            spinner would claim data is imminent; neither claim is one this page can back --
            an RPC call can fail, and there may be nothing else to show. */}
        {loading && auctions.length === 0 ? (
          <Loading
            className="mt-4"
            what="Reading rounds from the chain"
            detail={<>One eth_call per round against Base&rsquo;s public endpoint, plus a log scan for the bidders. The public RPC rate-limits, so this backs off and retries rather than hammering it — if it fails entirely the page falls back to the checked-in snapshot and says so.</>}
          />
        ) : error && auctions.length === 0 ? (
          <p className="mt-4 border border-brick bg-brick-soft px-3 py-2 text-sm text-brick">
            Could not read any round: {error}
          </p>
        ) : (
          <div className="mt-4">
            <RoundsFilterTabs
              auctions={auctions}
              head={head}
              active={filterId}
              onChange={setFilterId}
            />
            <p className="mt-2 text-[0.78rem] text-ink-faint">
              {filter.blurb}{" "}
              <span className="tnum text-ink-soft">
                Showing {shown.length} of {auctions.length}.
              </span>
              {unreadable > 0 && (
                <>
                  {" "}
                  <span className="text-amber">
                    {unreadable} round{unreadable === 1 ? "" : "s"} could not be read, so
                    they are not counted in any bid-based filter rather than being counted
                    as having none.
                  </span>
                </>
              )}
            </p>

            {shown.length === 0 ? (
              // An empty result is a real answer about the chain, not a failure, and it
              // says which question it is the answer to.
              <p className="mt-4 border border-rule bg-raised rounded-card px-4 py-6 text-sm text-ink-soft">
                No round matches &ldquo;{filter.label}&rdquo; in the {auctions.length} round
                {auctions.length === 1 ? "" : "s"} this build can see.
              </p>
            ) : (
              <div className="mt-3">
                <RoundsTable auctions={shown} head={head} />
              </div>
            )}
          </div>
        )}

        {/* An error alongside data that DID load is a different, quieter claim -- the rows
            below are real, but the last attempt to refresh them failed, so say that instead
            of silently swallowing it. */}
        {error && auctions.length > 0 ? (
          <p className="mt-3 text-[0.78rem] text-brick">
            Last refresh failed ({error}) -- showing the most recent successful read.
          </p>
        ) : null}

        <figcaption className="mt-3 text-[0.78rem] text-ink-faint">
          <span className="text-ink-soft">What produced this:</span> {caption}
        </figcaption>
      </figure>
    </main>
  );
}
