// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import { Test } from "forge-std/Test.sol";
import { console } from "forge-std/console.sol";

import { ISwapVM } from "@1inch/swap-vm/src/interfaces/ISwapVM.sol";
import { MakerTraits, MakerTraitsLib } from "@1inch/swap-vm/src/libs/MakerTraits.sol";
import { XYCSwap } from "@1inch/swap-vm/src/instructions/XYCSwap.sol";

import { GlasshouseAuction } from "../../src/instructions/GlasshouseAuction.sol";

/// @title Precompute the keeper's rounds
///
/// @notice The keeper opens a new auction every few minutes, and each one needs a DISTINCT
///         order: `Aqua.ship` rejects a strategy hash it has seen and `Book.open` rejects
///         an order hash it has opened. `postTransferInData` is the lever -- MakerTraits
///         concatenates it into `order.data` so it changes the hash, while the Book ignores
///         it entirely (its `postTransferIn` takes both hook-data arguments unnamed,
///         `GlasshouseBook.sol:245-246`). `test_Preflight_ARoundCounterGivesAFreshOrderHash`
///         pins that.
///
///         WHY A TABLE RATHER THAN COMPUTING IT IN THE KEEPER. Building an order means
///         upstream's bit packing: flag bits, a receiver, and four length-derived indexes
///         packed into `traits`. Reimplementing that in TypeScript is exactly how you get
///         an order that can never be filled, and the keeper would discover it only after
///         spending gas. So the orders are built HERE, by upstream's own library, and
///         written out as a table the keeper reads. Nothing is hand-packed anywhere.
///
///         Run:
///           forge test --match-contract GenerateRounds -vv
///         Writes `config/rounds.json`.
contract GenerateRoundsTest is Test {
    address internal constant BOOK = 0xc4ea91Fe700918220423ac307C6B1c59650FFbfe;
    address internal constant MAKER = 0xeEbf737F92C8F0d9070f35a7D9BAf416923bEcDf;
    address internal constant WETH = 0x4200000000000000000000000000000000000006;
    address internal constant USDC = 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913;
    uint24 internal constant MAX_BPS = 500;

    /// @dev 300 rounds at roughly two minutes each is about ten hours of keeper runtime,
    ///      which covers the demo window with room to spare. Regenerate for more.
    uint32 internal constant ROUNDS = 300;

    function _orderForRound(uint32 round) internal pure returns (ISwapVM.Order memory) {
        return MakerTraitsLib.build(
            MakerTraitsLib.Args({
                maker: MAKER,
                tokenA: WETH,
                tokenB: USDC,
                shouldUnwrapWeth: false,
                useAquaInsteadOfSignature: true,
                allowZeroAmountIn: false,
                receiver: address(0),
                hasPreTransferInHook: false,
                hasPostTransferInHook: true,
                hasPreTransferOutHook: false,
                hasPostTransferOutHook: false,
                preTransferInTarget: address(0),
                preTransferInData: "",
                postTransferInTarget: BOOK,
                postTransferInData: abi.encodePacked(round),
                preTransferOutTarget: address(0),
                preTransferOutData: "",
                postTransferOutTarget: address(0),
                postTransferOutData: "",
                program: bytes.concat(GlasshouseAuction.build(BOOK, MAX_BPS), XYCSwap.build())
            })
        );
    }

    function test_GenerateRoundsTable() public {
        string memory out = '{\n  "note": "GENERATED by test/fork/GenerateRounds.t.sol. Do not edit.",\n';
        out = string.concat(out, '  "maker": "', vm.toString(MAKER), '",\n');
        out = string.concat(out, '  "book": "', vm.toString(BOOK), '",\n');
        out = string.concat(out, '  "maxBps": ', vm.toString(uint256(MAX_BPS)), ",\n");
        out = string.concat(out, '  "rounds": [\n');

        // Every hash must be distinct, or the keeper would silently stop opening auctions
        // after the first collision. Checked here rather than discovered on chain.
        bytes32 previous;
        for (uint32 r = 0; r < ROUNDS; r++) {
            ISwapVM.Order memory o = _orderForRound(r);
            bytes32 h = keccak256(abi.encode(o));
            if (r > 0) assertTrue(h != previous, "consecutive rounds must not collide");
            previous = h;

            out = string.concat(
                out,
                '    { "round": ', vm.toString(uint256(r)),
                ', "traits": "', vm.toString(MakerTraits.unwrap(o.traits)),
                '", "data": "', vm.toString(o.data),
                '", "orderHash": "', vm.toString(h), '" }',
                r + 1 == ROUNDS ? "\n" : ",\n"
            );
        }
        out = string.concat(out, "  ]\n}\n");
        vm.writeFile("config/rounds.json", out);

        ISwapVM.Order memory first = _orderForRound(0);
        console.log("");
        console.log("   wrote config/rounds.json with %s rounds", ROUNDS);
        console.log("   round 0 hash  %s", vm.toString(keccak256(abi.encode(first))));
        console.log("   round 1 hash  %s", vm.toString(keccak256(abi.encode(_orderForRound(1)))));
        console.log("");
    }

    /// @dev The counter must not disturb the program. A round whose gate had been displaced
    ///      would still open and still fill -- at the base price, proving nothing -- so this
    ///      is checked for every round rather than spot-checked.
    function test_EveryRoundKeepsTheGateFirst() public pure {
        bytes memory program = bytes.concat(GlasshouseAuction.build(BOOK, MAX_BPS), XYCSwap.build());
        for (uint32 r = 0; r < 25; r++) {
            bytes memory data = _orderForRound(r).data;
            bool found;
            for (uint256 i = 0; i + program.length <= data.length; i++) {
                bool same = true;
                for (uint256 j; j < program.length; j++) {
                    if (data[i + j] != program[j]) { same = false; break; }
                }
                if (same) { found = true; break; }
            }
            assertTrue(found, "the gate must survive the round counter in every round");
        }
    }
}
